// school-club-registration/src/main/webapp/app/entities/club/detail/club-detail.component.ts
import { Component, input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { IClub } from '../club.model';

@Component({
  selector: 'jhi-club-detail',
  templateUrl: './club-detail.component.html',
  imports: [SharedModule, RouterModule],
})
export class ClubDetailComponent {
  club = input<IClub | null>(null);

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (club(); as clubRef) {
      <div>
        <h2 data-cy="clubDetailsHeading"><span>Club</span></h2>

        <hr />

        <jhi-alert-error />

        <jhi-alert />

        <dl class="row-md jh-entity-details">
          <dt><span>ID</span></dt>
          <dd>
            <span>{{ clubRef.id }}</span>
          </dd>
          <dt><span>Name</span></dt>
          <dd>
            <span>{{ clubRef.name }}</span>
          </dd>
          <dt><span>Description</span></dt>
          <dd>
            <span>{{ clubRef.description }}</span>
          </dd>
          <dt><span>Max Members</span></dt>
          <dd>
            <span>{{ clubRef.maxMembers }}</span>
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span>Back</span>
        </button>

        <button type="button" [routerLink]="['/club', clubRef.id, 'edit']" class="btn btn-primary">
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span>Edit</span>
        </button>
      </div>
    }
  </div>
</div>

// register-club-copy/src/main/webapp/app/entities/club/club-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Col, Row } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './club.reducer';

export const ClubDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const clubEntity = useAppSelector(state => state.club.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="clubDetailsHeading">
          <Translate contentKey="registerClubApp.club.detail.title">Club</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{clubEntity.id}</dd>
          <dt>
            <span id="name">
              <Translate contentKey="registerClubApp.club.name">Name</Translate>
            </span>
          </dt>
          <dd>{clubEntity.name}</dd>
          <dt>
            <span id="description">
              <Translate contentKey="registerClubApp.club.description">Description</Translate>
            </span>
          </dt>
          <dd>{clubEntity.description}</dd>
        </dl>
        <Button tag={Link} to="/club" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/club/${clubEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default ClubDetail;
